NOMBRES:

## Sergio Rodrigo Cárdenas Rivera


*Durante este ejercicio 50% de la calificación corresponde a resolver los problemas, y 50% al trabajo colaborativo.*

**Ejercicio 1**

Supongamos que tienes datos climáticos diarios de 4 ciudades durante una semana contenidos en la lista "clima". Cada fila representa un día, y cada columna representa una ciudad. Usando funciones en NumPy realizar las siguientes operaciones:
1. Calcula el promedio de temperatura de cada ciudad durante la semana.
2. Determina el día más caluroso (máxima temperatura) para cada ciudad.
3. Genera una nueva matriz donde cada elemento indique si la temperatura fue superior al promedio semanal de su ciudad.

Comenta tu codigo para conocer el razonamiento usado para resolver el problema.

In [23]:
clima = [
  [25, 30, 35, 28],
  [24, 31, 34, 27],
  [23, 32, 36, 29],
  [26, 33, 37, 30],
  [25, 30, 35, 28],
  [27, 29, 34, 26],
  [26, 31, 33, 27]
]

In [30]:
#1
import numpy as np

arr = np.array(clima)
prom = arr.mean(axis=0)
prom_temp_x_ciudad = np.round(prom, decimals=2)
print('Promedio de temp por ciudad', prom_temp_x_ciudad)

Promedio de temp por ciudad [25.14 30.86 34.86 27.86]


In [31]:
#2
max_temp = arr.max(axis=0)
print('Maxima temp pore ciudad', max_temp)
pos_max_temp = arr.argmax(axis=0)
print('Dia de max temp por ciudad', pos_max_temp)

Maxima temp pore ciudad [27 33 37 30]
Dia de max temp por ciudad [5 3 3 3]


In [35]:
#3
temp_sup_prom = arr > prom_temp_x_ciudad
print('Dias que la temperatura fue mayor al prom.\n',temp_sup_prom)

Dias que la temperatura fue mayor al prom.
 [[False False  True  True]
 [False  True False False]
 [False  True  True  True]
 [ True  True  True  True]
 [False False  True  True]
 [ True False False False]
 [ True  True False False]]


**Ejercicio 2: Operaciones con matrices grandes**

Genera dos matrices aleatorias de tamaño 5x5 con números enteros entre 10 y 50. Realiza las siguientes operaciones:

1. Suma las dos matrices y guarda el resultado.
2. Calcula el producto elemento a elemento de las dos matrices.
3. Encuentra el promedio de todos los elementos de la matriz resultante del producto.
4. Reemplaza todos los valores menores que el promedio en la matriz producto por 0.

In [38]:
import numpy as np 

m1 = np.random.randint(10, 51, size=(5, 5))
m2 = np.random.randint(10, 51, size=(5, 5))

print(m1)
print()
print(m2)

[[49 44 34 10 12]
 [23 27 50 15 32]
 [44 32 31 33 31]
 [37 42 24 41 38]
 [43 20 27 41 38]]

[[43 22 40 37 12]
 [14 23 22 36 18]
 [43 16 35 16 50]
 [49 11 40 44 34]
 [46 48 48 40 13]]


In [41]:
#1
suma = m1 + m2
suma

array([[92, 66, 74, 47, 24],
       [37, 50, 72, 51, 50],
       [87, 48, 66, 49, 81],
       [86, 53, 64, 85, 72],
       [89, 68, 75, 81, 51]])

In [42]:
#2
prod = m1 * m2
prod

array([[2107,  968, 1360,  370,  144],
       [ 322,  621, 1100,  540,  576],
       [1892,  512, 1085,  528, 1550],
       [1813,  462,  960, 1804, 1292],
       [1978,  960, 1296, 1640,  494]])

In [47]:
#3
prom_prod = np.average(prod)
print('Prom matrix producto:', prom_prod)


Prom matrix producto: 1054.96


In [48]:
#4
m_remp = np.where(prod < prom_prod, 0, prod)
m_remp

array([[2107,    0, 1360,    0,    0],
       [   0,    0, 1100,    0,    0],
       [1892,    0, 1085,    0, 1550],
       [1813,    0,    0, 1804, 1292],
       [1978,    0, 1296, 1640,    0]])

**Ejercicio 3: Transformación y análisis de un conjunto de datos**

El conjunto de datos presentado en "ventas" simula datos de ventas de 3 productos en 10 días. Cada columna representa un producto y cada fila un día. Realiza las siguientes operaciones:

1. Calcula el total de ventas por producto (suma por columna).
2. Encuentra el día con mayores ventas totales.
3. Identifica si hay algún día en que todos los productos tuvieron ventas superiores a 100.

In [49]:
import numpy as np
ventas = np.random.randint(50,150, size=(10,3))
ventas

array([[ 71, 129,  77],
       [ 57, 123, 109],
       [136,  99,  80],
       [132, 114,  75],
       [108, 126,  58],
       [126, 126, 136],
       [ 93, 138,  52],
       [ 68, 122, 109],
       [103, 149,  81],
       [ 97,  97,  84]])

In [52]:
#1
total_ventas_prod = ventas.sum(axis=0)
print('Total de ventas por prod.', total_ventas_prod)

Total de ventas por prod. [ 991 1223  861]


In [54]:
#2
dia_may_venta = ventas.argmax(axis=0)
print('Dia de mayor venta', dia_may_venta)

Dia de mayor venta [2 8 5]


In [58]:
#3
dia_ventas_may_100 = ventas > 100
print('Dia con ventas mayores a 100\n', dia_ventas_may_100)

Dia con ventas mayores a 100
 [[False  True False]
 [False  True  True]
 [ True False False]
 [ True  True False]
 [ True  True False]
 [ True  True  True]
 [False  True False]
 [False  True  True]
 [ True  True False]
 [False False False]]


**Ejercicio 4**

Simula un dataset con datos faltantes:

1. Genera un array 2D de 5x5 con valores aleatorios entre 1 y 100.
2. Reemplaza aleatoriamente el 20% de los valores con np.nan para simular datos faltantes.

Escribe una función que:
1. Reemplace los valores faltantes con la media de su columna.
2. Devuelva el array modificado.

In [106]:
#1
m = np.random.randint(1, 101, size=(5, 5))
m

array([[35, 36, 68, 13,  6],
       [47, 77, 60, 79, 40],
       [ 8, 24, 86, 69, 17],
       [73, 69, 92, 98, 67],
       [52, 37, 95, 78, 22]])

In [107]:
#2
m = m.astype(float)
ranIndex = np.random.choice(m.size, 5, replace=False)
m.ravel()[ranIndex] = np.nan
m

array([[35., 36., 68., 13.,  6.],
       [nan, 77., 60., 79., nan],
       [ 8., 24., 86., nan, 17.],
       [73., 69., 92., 98., 67.],
       [52., 37., nan, nan, 22.]])

In [ ]:
#1 y 2
def remplaza_valores_faltantes(matrix):
  media_col = np.nanmean(matrix, axis=0)
  inds = np.where(np.isnan(matrix))
  matrix[inds] = np.take(media_col, inds[1])
  return matrix

ans = remplaza_valores_faltantes(matrix=m) #devuelve el array modif.
print(m)

[[35.         36.         68.         13.          6.        ]
 [42.         77.         60.         79.         28.        ]
 [ 8.         24.         86.         63.33333333 17.        ]
 [73.         69.         92.         98.         67.        ]
 [52.         37.         76.5        63.33333333 22.        ]]


In [ ]:
#2
