NOMBRES:
Paola Ximena Aguilar Quiñones
Maria Ines Argote Coca
Sergio Cardenas

*Durante este ejercicio 50% de la calificación corresponde a resolver los problemas, y 50% al trabajo colaborativo.*

**Ejercicio 1**

Supongamos que tienes datos climáticos diarios de 4 ciudades durante una semana contenidos en la lista "clima". Cada fila representa un día, y cada columna representa una ciudad. Usando funciones en NumPy realizar las siguientes operaciones:
1. Calcula el promedio de temperatura de cada ciudad durante la semana.
2. Determina el día más caluroso (máxima temperatura) para cada ciudad.
3. Genera una nueva matriz donde cada elemento indique si la temperatura fue superior al promedio semanal de su ciudad.

Comenta tu codigo para conocer el razonamiento usado para resolver el problema.

In [4]:
import numpy as np
clima = [[25, 30, 35, 28],
         [24, 31, 34, 27],
         [23, 32, 36, 29],
         [26, 33, 37, 30],
         [25, 30, 35, 28],
         [27, 29, 34, 26],
         [26, 31, 33, 27]]

In [12]:
# Ejercicio 1 
average = np.mean(clima, axis=0)
print(average)

[25.14285714 30.85714286 34.85714286 27.85714286]


In [13]:
# Ejercicio 2
maxTemp = np.max(clima, axis=0)
indexMaxTemp = np.argmax(clima, axis=0)
print(maxTemp)
print(indexMaxTemp)

[27 33 37 30]
[5 3 3 3]


In [16]:
# Ejercicio 3
lenghtM = np.shape(clima)
superior_promedio = clima > average
print(superior_promedio)

[[False False  True  True]
 [False  True False False]
 [False  True  True  True]
 [ True  True  True  True]
 [False False  True  True]
 [ True False False False]
 [ True  True False False]]


**Ejercicio 2: Operaciones con matrices grandes**

Genera dos matrices aleatorias de tamaño 5x5 con números enteros entre 10 y 50. Realiza las siguientes operaciones:

1. Suma las dos matrices y guarda el resultado.
2. Calcula el producto elemento a elemento de las dos matrices.
3. Encuentra el promedio de todos los elementos de la matriz resultante del producto.
4. Reemplaza todos los valores menores que el promedio en la matriz producto por 0.

In [1]:
import numpy as np

np.random.seed(0)  # Para reproducibilidad
matriz1 = np.random.randint(10, 51, size=(5, 5))
matriz2 = np.random.randint(10, 51, size=(5, 5))

In [2]:
matriz1

array([[10, 13, 13, 49, 19],
       [29, 31, 46, 33, 16],
       [34, 34, 22, 11, 48],
       [49, 33, 34, 27, 47],
       [35, 23, 18, 19, 30]])

In [3]:
matriz2

array([[26, 15, 25, 10, 28],
       [45, 34, 39, 29, 29],
       [24, 49, 42, 11, 19],
       [42, 41, 20, 33, 45],
       [21, 38, 44, 10, 10]])

In [4]:
# 1. Sumar  matrices y guardar el resultado
suma_matrices = matriz1 + matriz2
suma_matrices

array([[36, 28, 38, 59, 47],
       [74, 65, 85, 62, 45],
       [58, 83, 64, 22, 67],
       [91, 74, 54, 60, 92],
       [56, 61, 62, 29, 40]])

In [5]:
producto_matrices = matriz1 * matriz2
producto_matrices

array([[ 260,  195,  325,  490,  532],
       [1305, 1054, 1794,  957,  464],
       [ 816, 1666,  924,  121,  912],
       [2058, 1353,  680,  891, 2115],
       [ 735,  874,  792,  190,  300]])

In [6]:
promedio_producto = np.mean(producto_matrices)
promedio_producto

872.12

In [7]:
np.where(producto_matrices < promedio_producto, 0, producto_matrices)

array([[   0,    0,    0,    0,    0],
       [1305, 1054, 1794,  957,    0],
       [   0, 1666,  924,    0,  912],
       [2058, 1353,    0,  891, 2115],
       [   0,  874,    0,    0,    0]])

**Ejercicio 3: Transformación y análisis de un conjunto de datos**

El conjunto de datos presentado en "ventas" simula datos de ventas de 3 productos en 10 días. Cada columna representa un producto y cada fila un día. Realiza las siguientes operaciones:

1. Calcula el total de ventas por producto (suma por columna).
2. Encuentra el día con mayores ventas totales.
3. Identifica si hay algún día en que todos los productos tuvieron ventas superiores a 100.

In [8]:
import numpy as np
ventas = np.random.randint(50,150, size=(10,3))
ventas

array([[ 86, 103,  55],
       [ 88,  67, 129],
       [ 54,  92, 108],
       [ 81,  51, 115],
       [ 91, 107,  85],
       [ 61,  96, 132],
       [141,  50,  64],
       [149, 103,  62],
       [ 92, 134, 125],
       [118,  56, 118]])

In [10]:
# 1
ventas.sum(axis=0)

array([961, 859, 993])

In [13]:
#2
diaMayVenta = np.argmax(ventas, axis=0)
diaMayVenta

array([7, 8, 5], dtype=int64)

In [14]:
#3
ventas > 100

array([[False,  True, False],
       [False, False,  True],
       [False, False,  True],
       [False, False,  True],
       [False,  True, False],
       [False, False,  True],
       [ True, False, False],
       [ True,  True, False],
       [False,  True,  True],
       [ True, False,  True]])

**Ejercicio 4**

Simula un dataset con datos faltantes:

1. Genera un array 2D de 5x5 con valores aleatorios entre 1 y 100.
2. Reemplaza aleatoriamente el 20% de los valores con np.nan para simular datos faltantes.

Escribe una función que:
1. Reemplace los valores faltantes con la media de su columna.
2. Devuelva el array modificado.

In [25]:
#1
matrix = np.random.randint(1, 101, size=(5,5))
matrix

array([[ 83,  69,  23, 100,  84],
       [  8,  73,  62,  14,   6],
       [  1,   9,  80,  80,  54],
       [ 12,   5,  40,  93,  46],
       [ 27,  75,  53,  50,  92]])

In [26]:
#2
matrix = matrix.astype(float)
ranIndex= np.random.choice(matrix.size, 5, replace=False)
matrix.ravel()[ranIndex] = np.nan
matrix


array([[ 83.,  69.,  23., 100.,  84.],
       [  8.,  73.,  nan,  14.,   6.],
       [  1.,   9.,  80.,  80.,  nan],
       [ nan,   5.,  nan,  93.,  46.],
       [ 27.,  75.,  nan,  50.,  92.]])

In [29]:
#3
def replaceMeanColumn(matrix):
    colsMean = np.nanmean(matrix, axis=0)
    print(colsMean)


replaceMeanColumn(m)


array([29.75, 46.2 , 51.5 , 67.4 , 57.  ])